#Jaeveous Hardy
#June 23, 2024
#P2HW1
#Calculating and displaying travel expenses
print('This program calculates and displays travel expenses')
print()
print('Enter Budget:', end=' ')
budget = float(input())
print('Enter your travel destination:', end=' ')
destination = input()
print('How much do you think you will spend on gas?', end=' ')
gas = float(input())
print('Approximately, how much will need for accomodation/hotel?', end=' ')
hotel = float(input())
print('Last, how much do you need for food?', end=' ')
food = float(input())
print()
print('------------Travel expenses------------')
print('Location:', destination)
print(f'Initial Budget: ${budget: .2f}')
print(f'Fuel: ${gas: .2f}')
print(f'Accomodation: ${hotel: .2f}')
print(f'Food: ${food: .2f}')
print('---------------------------------------')
print()
print()
print(f'Remaining Balance: ${budget-gas-hotel-food: .2f}')
